In [1]:
import tensorflow as tf

print(tf.__version__)



2.6.0


In [6]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.59209883, -0.2840461 , -0.38434917,  0.6033891 , -0.3753352 ,
        -0.18400562,  0.39623535, -0.5327121 , -0.09120029,  0.10516372]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.16917807, 0.07044321, 0.06372034, 0.17109896, 0.06429732,
        0.07785495, 0.13908543, 0.05493446, 0.08542619, 0.1039611 ]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)


Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2990 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1438 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1069 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0870 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0753 - accuracy: 0.9762
313/313 - 0s - loss: 0.0810 - accuracy: 0.9755


[0.08096563816070557, 0.9754999876022339]

In [3]:
import tensorflow as tf

# Uncomment to see where your variables get placed (see below)
# tf.debugging.set_log_device_placement(True)

my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])
print(complex_variable)

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>


In [4]:
import numpy as np

a1D = np.array([1,2,3,4])
a1D

array([1, 2, 3, 4])

In [5]:
a2D = np.array([[1,2,3],[4,5,6]])
a2D

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a1D2 = np.array([0,1,1,1])
ans = a1D - a1D2
ans

array([1, 1, 2, 3])

In [9]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

lo= Dense(units=1,input_shape=[1])
model = Sequential([lo])
model.compile(optimizer='sgd',loss='mean_squared_error')

xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model.fit(xs,ys,epochs=500)
print(model.predict([10.0]))
print("Here is what I learned: {}".format(lo.get_weights()))

Epoch 1/500
1/1 [==============================] - 0s 216ms/step - loss: 23.8909
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 19.0814
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 15.2916
Epoch 4/500
1/1 [==============================] - 0s 983us/step - loss: 12.3042
Epoch 5/500
1/1 [==============================] - 0s 1ms/step - loss: 9.9483
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 8.0893
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 6.6213
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 5.4611
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 4.5431
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 3.8158
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 3.2387
Epoch 12/500
1/1 [==============================] - 0s 3ms/step - loss: 2.7797
Epoch 13/500
1/1 [==============================] - 0

In [10]:
print(model.predict([4]))

[[6.9973907]]


In [11]:
!pip install pillow

In [12]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
'Today is a sunny day',
'Today is a rainy day'
]

token = Tokenizer(num_words=100)
token.fit_on_texts(sentences)
word_index = token.word_index
print(word_index)



{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}


In [16]:
seq = token.texts_to_sequences(sentences)
seq

[[1, 2, 3, 5, 4], [1, 2, 3, 6, 4]]

In [18]:
sequences = token.texts_to_sequences(sentences)
test_sequences = token.texts_to_sequences(sentences)
print(word_index)
print(test_sequences)

{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}
[[1, 2, 3, 5, 4], [1, 2, 3, 6, 4]]


In [25]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
'Today is a sunny day',
'Today is a rainy day',
'Is it sunny today?',
'I really enjoyed walking in the snow today'
]

#paded = pad_sequences(sentences)
#print(paded)
from bs4 import BeautifulSoup
soup = BeautifulSoup(sentences)
sentence = soup.get_text()

TypeError: expected string or bytes-like object

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
import tensorflow as tf
import timeit
from datetime import datetime
# Define a Python function.
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()
assert(orig_value == tf_function_value)

In [5]:
import tensorflow as tf
from datetime import datetime

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [7]:
class SimpleModel(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0,name='train_me')
        self.non_trainable_variable = tf.Variable(5.0,trainable=False, name='no_not_train_me')

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModel(name="simple")

simple_module(tf.constant(5.0))

<tf.Tensor: shape=(), dtype=float32, numpy=30.0>

In [11]:
pip show tensorflow

SyntaxError: invalid syntax (Temp/ipykernel_17260/3847666901.py, line 1)